### ISSUE TITLE
请教几个思路

### ISSUE THREAD

**Issue by forever-z-133** [HarryChen0506/malyan#8]
你好，我也有意想写个 2d 引擎，以 css 的和 vdom 的方式来布局，
但有几道砍总是过不去，想找大佬请教一下，探讨下思路亦可。

1. 尺寸联动问题。比如子级尺寸变大，父级是类似 inline-block 的包裹型元素，父级也将尺寸变大，继而祖父或兄弟的尺寸也会变化，这类问题大佬你会怎么去解决？

2. 文本换行和省略问题。免不了会不断用 measureText 去计算，不知有没有其他思路。

3. 元素超出与裁剪问题。譬如 background-image 和 overflow 效果，在 canvas 中做裁剪稍有麻烦，clip 性能在小程序上非常差，用 globalCompositeOperation 又有作用域问题。

4. 组件问题。譬如 scroll-view 组件，与普通元素稍有不同，除了 clientHeight 还会有 scrollHeight 之类的内部参数和事件呢，如何能比较好的兼容拓展？

**Comment by HarryChen0506** [comment]
你有项目地址吗，或者现有的例子？我感觉你的项目难度有些高呢。感觉是要做成跑在canvas里的HTML元素或组件呢😂

**Comment by forever-z-133** [comment]
https://github.com/forever-z-133/wechat-game-components
惭愧，连基础组件都还没搭好，上面的几个问题卡好久了。

**Comment by forever-z-133** [comment]
https://github.com/forever-z-133/zyh-canvas
原来我还写过一个，这个要更接近我的思路一些。

**Comment by HarryChen0506** [comment]
1. 尺寸问题。我的方案是父子间不相互影响对方的尺寸，渲染图形也是根据矩阵变换的方式进行的。你想做到类似HTML元素那样的继承宽度或者其他特性，难度要大些。
2. 文本换行和省略，我也只能想到measureText的方案
3. 微信里裁剪用clip的性能问题我没有研究过
4. scroll-view我也不太熟悉呢，事件的话，自己定义事件参数就好了
